name: devi
description: Devi is a fast and light framework for flutter to make work easy, Its allow to management for route, disk storage, alerts and validation.
version: 1.0.3
homepage: rohitchouhan.com
repository: https://github.com/rohit-chouhan/devi

environment:
  sdk: ">=2.18.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: 2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

screenshots:
  - description: 'Devi'
    path: logo.png

topics:
  - get
  - provider
  - alert
  - bloc
