name: Publish Flutter Package

on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Decode credentials
      id: decode_credentials
      run: echo "${{ secrets.CREDENTIAL_JSON }}" | base64 --decode > $HOME/.pub-cache/credentials.json

    - name: Publish to pub.dev
      run: flutter pub publish --force
      env:
        PUB_CREDENTIALS: ${{ secrets.CREDENTIAL_JSON }}
